### ISSUE TITLE
M1 not starting

### ISSUE THREAD

**Issue by soejrd** [FahimF/sd-gui#12]
I'm getting this error on a M1 Pro 2021 MacBook 

Intel MKL FATAL ERROR: This system does not meet the minimum requirements for use of the Intel(R) Math Kernel Library.
The processor must support the Intel(R) Supplemental Streaming SIMD Extensions 3 (Intel(R) SSSE3) instructions.
The processor must support the Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) instructions.
The processor must support the Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

**Comment by FahimF** [comment]
Not sure that's from my code? When do you get this error? Or rather, what did you do just before you got that error?

**Comment by soejrd** [comment]
I ran the following commands and got this error in return:

conda activate ml
cd sd-gui
python app.py

After some googling I found a fix/solution that works:

1. Uninstall PyTorch using conda (if it is installed): conda remove pytorch
2. Install it using pip: pip install torch

**Comment by FahimF** [comment]
Since Pytorch is a bit iffy with pip (I had no luck a couple of weeks back) it might work or it might not. But do give it a short. But also note that if you do "pip install torch", it will install the stable builds and my GUI (and Stable Diffusion in general) will probably not work with Pytorch stable builds. You need nightlies if you want MPS support and the speed bump it brings along.

Google for "install pytorch nightly using pip" and you should find the command ... I believe it involves the "--pre" switch but also might need to point at a particular build or at nightly servers.
