### ISSUE TITLE
No module named 'diffusers'

### ISSUE THREAD

**Issue by MrKuenning** [FahimF/sd-gui#14]
Windows 10 Here,

Followed the windows guide but when I run "python app.py"  I get the following:

```
Traceback (most recent call last):
  File "E:\Machine Learning\SDGUI-FahimF\sd-gui\app.py", line 5, in <module>
    from tools.config import Config
  File "E:\Machine Learning\SDGUI-FahimF\sd-gui\tools\config.py", line 7, in <module>
    from tools.sd_engine import GeneratorType
  File "E:\Machine Learning\SDGUI-FahimF\sd-gui\tools\sd_engine.py", line 2, in <module>
    from diffusers import StableDiffusionPipeline, StableDiffusionInpaintPipeline, StableDiffusionImg2ImgPipeline
ModuleNotFoundError: No module named 'diffusers'
```

**Comment by Gitterman69** [comment]
Activate your conda environment and reinstall

`conda activate ml` then reinstall (maybe delete sd-gui folder first)

you can also 
```
conda activate ml
pip install diffusers
pip install XYZ(WHATEVER ELSE COMES UP)
```

**Comment by FahimF** [comment]
You don't need to delete the sd-gui folder since it won't have any effect on your Python packages but the rest holds 🙂 Python packages seem to get lots sometimes due to conflicts between packages or because something didn't get installed properly. So reinstall via either conda (preferred) or pip should do the trick.
