### ISSUE TITLE
Prompt text in ui is invisible/white?

### ISSUE THREAD

**Issue by Vrk3ds** [FahimF/sd-gui#17]
I finally was able to get this running on my system which is:

Mac Studio m1 Ultra 64gb running Monteray 12.6

But the text in the prompt fields is either invisible or most likely white.

See attached
![dark_theme](https://user-images.githubusercontent.com/53342535/193682659-abf9adf9-cecc-4d73-8620-5aa6bd22ae4a.jpg)

**Comment by FahimF** [comment]
I had not tested under Dark Mode since I generally use Light Mode. My bad. If I am in Light Mode, have the app running and then switch to Dark Mode, the text shows correctly. But if I turn on Dark Mode and then run the app, then the text is indeed hidden. Looks like a bug in the UI framework. Will see what can be done. But for the time being, if you run in Light Mode the text should display correctly ...

**Comment by FahimF** [comment]
There's a new change to the code which fixes this issue. But you'll need to add a new package to the environment by running the following command:
`pip install darkdetect`

Also, you'd need to pull the latest code from the Git repo 🙂
