### ISSUE TITLE
darkdetect and skimage. (Manually had to be installed)

### ISSUE THREAD

**Issue by HugoSega** [FahimF/sd-gui#20]
Great new interface! Thanks for your hard work beautiful job!

Here is what I had to do to run in on my M1
after the auto-installation script, I had to manually install darkdetect and skimage.

Instructions:
pip install darkdetect
conda install -c conda-forge scikit-image

**Comment by FahimF** [comment]
I do have darkdetect in the instructions - that was updated yesterday. Maybe you had downloaded previously? I believe scikit-image has been there in the instructions from the beginning too ... But if you used the installer script, then that might explain it since that one might not have had those added. I think I have a caveat about the installer not working correctly and so I haven't been updating it as much since it needs a complete overhaul 🙂

**Comment by HugoSega** [comment]
That's correct Fahim, I used the installer script. 

P.S
and again inpaint feature and gallery feature are really nice.

**Comment by FahimF** [comment]
Ah, yes, then it would make sense, sorry about that 🙂 The installer seems to work great for some (possibly because they had conda installed already) but for others it breaks horribly because after installing conda, you need to exit the terminal and get back in for the conda environment variables to take effect.

So I need to revamp the installer script so that it exits at the right point and them picks up again when you run it again. But haven't had the time to do it.

Glad you like the inpainting and outpainting! Hope it works well for you? Some people had trouble figuring out how to use it and I do need to add a guide on that stuff somewhere but again, need to find the time 😛

**Comment by HugoSega** [comment]
> Ah, yes, then it would make sense, sorry about that 🙂 The installer seems to work great for some (possibly because they had conda installed already) but for others it breaks horribly because after installing conda, you need to exit the terminal and get back in for the conda environment variables to take effect.
> 
> So I need to revamp the installer script so that it exits at the right point and then picks up again when you run it again. But haven't had the time to do it.
> 
> Glad you like the inpainting and outpainting! Hope it works well for you? Some people had trouble figuring out how to use it and I do need to add a guide on that stuff somewhere but again, need to find the time 😛

I really enjoy Inpaint/outpaint feature and the gallery is really helpful and very informative.  I know it is a lot of coding and time-consuming and thanks for that.

P.S
Eular-A sampler would be really helpful.

**Comment by FahimF** [comment]
For Euler and some of the others, the current Hugging Face diffusers-based Stable Diffusion implementation won't work. Or at least, it won't work as is. I'm looking at switching over to the ComVis SD implementation so that I can support extra schedulers like Euler and others, and also to provide additional features like negative prompts, and a few other things which are much more easier to implement on that side of the fence 🙂

**Comment by HugoSega** [comment]
> For Euler and some of the others, the current Hugging Face diffusers-based Stable Diffusion implementation won't work. Or at least, it won't work as is. I'm looking at switching over to the ComVis SD implementation so that I can support extra schedulers like Euler and others, and also to provide additional features like negative prompts, and a few other things which are much more easier to implement on that side of the fence 🙂

Sound like totally different architecture, and a lot of work. I wish I knew basic coding to somehow be helpful, but all I can do is a test and I will definitely do that on every update you will post.

**Comment by FahimF** [comment]
Thank you :smile The testing helps greatly! I don't always have the time to test everything and only the features I use a lot get tested thoroughly. So any testing (and bug reports) are always much appreciated.
