### ISSUE TITLE
Local Stable-Diffusion-v1-4 model use

### ISSUE THREAD

**Issue by nickraimondi** [FahimF/sd-gui#3]
Great project! I look forward to seeing how this grows with Stable Diffusion. I can get the UI to load and it looks amazing, but I was hoping to use a locally stored version of Stable-Diffusion-v1-4, without the need to authenticate into Hugging Face. Is there anything I can do to allow me to point to my local copy to use as an offline source??

**Comment by FahimF** [comment]
Thanks for the kind words!

The code does use a local copy 😄 The instructions are for people who don't already have a local copy. What the instructions do is simply create a folder named "stable-diffusion-v1-4" inside the sd-gui folder which contains the models. The authentication is due to Hugging Face requiring auth to download the initial copy via a git clone ... That's it.

So if you already have a copy on your hard drive, skip that step and simply copy the existing model (or create a symlink to it) so that you have a "stable-diffusion-v1-4" folder inside the sd-gui folder with the model data.
